version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  rabbitmq_publisher:
    build:
      context: ./RabbitMqPublisher
    depends_on:
      - rabbitmq

  rabbitmq_webapi:
    build:
      context: ./RabbitMqWebApi
    depends_on:
      - rabbitmq
    ports:
      - "5000:80"
